### ISSUE TITLE
what commands are use to run 

### ISSUE THREAD

**Issue by Zumkato** [isaiahsarju/dockerfiles#4]
I have created a build of this in my on GitHub but when I use yours or mines

I get a mongo connection to localhost error each time. 

any tips  or run command option i need

**Comment by isaiahsarju** [comment]
Zumkato,

My apologies for the delayed response. Please send the error. What's your environment (E.g. native docker in *nix, Mac with Docker machine, etc.)?

Isaiah

**Comment by Zumkato** [comment]
I am running docker on a Debian-based system 

After my build i run this command: 

docker run --rm -it -p 11013:11013 -p 11014:11014 -p 11015:11015 -p 11016:11016 lair2:test2

then I get his Error:

root@43507eb7d3d5:~/lair# ./start.sh 
rm: cannot remove 'db/mongod.lock': No such file or directory
Now using node v0.10.40 (npm v1.4.28)
Activating privacy features... done.
0.0.0.0:11013
2016/05/09 16:39:37 Could not connect to database. Error: no reachable servers

/root/lair/bundle/programs/server/node_modules/fibers/future.js:278
						throw(ex);
						      ^
Error: failed to connect to [localhost:11016]
    at Object.Future.wait (/root/lair/bundle/programs/server/node_modules/fibers/future.js:398:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:102:1)
    at AccountsServer.AccountsCommon (accounts_common.js:23:18)
    at new AccountsServer (accounts_server.js:16:5)
    at Package (globals_server.js:5:12)
    at /root/lair/bundle/programs/server/packages/accounts-base.js:1814:4
    - - - - -
    at [object Object].<anonymous> (/root/lair/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at [object Object].emit (events.js:106:17)
    at [object Object].<anonymous> (/root/lair/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/root/lair/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:448:13)

**Comment by isaiahsarju** [comment]
Zumkato,

Please try first updating to latest version of ubuntu image ```docker pull ubuntu:latest```
Then see README.md in lair folder with instructions.

Please let me know if that works

Isaiah
